# Generated by Django 5.0.10 on 2026-01-01 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BomTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('schema', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bom_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('project', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SIGNOFF_PENDING', 'Signoff pending'), ('APPROVAL_PENDING', 'Procurement approval pending'), ('APPROVED', 'Approved'), ('NEEDS_CHANGES', 'Needs changes'), ('ORDERED', 'Ordered'), ('RECEIVING', 'Receiving'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='DRAFT', max_length=32)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('cancel_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boms', to='boms.bomtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ProcurementApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('NEEDS_CHANGES', 'Needs changes'), ('CANCELED', 'Canceled')], default='PENDING', max_length=32)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='boms.bom')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcurementApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('NEEDS_CHANGES', 'Needs changes')], default='PENDING', max_length=32)),
                ('comment', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_approvals', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='boms.procurementapprovalrequest')),
            ],
        ),
        migrations.CreateModel(
            name='BomEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='boms.bom')),
            ],
            options={
                'indexes': [models.Index(fields=['bom', 'created_at'], name='boms_bomeve_bom_id_35ce62_idx'), models.Index(fields=['event_type', 'created_at'], name='boms_bomeve_event_t_8fe1ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='BomItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(blank=True, max_length=20)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('tax_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('link', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('signoff_status', models.CharField(choices=[('NONE', 'None'), ('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('NEEDS_CHANGES', 'Needs changes'), ('CANCELED', 'Canceled')], default='NONE', max_length=32)),
                ('signoff_comment', models.TextField(blank=True)),
                ('ordered_at', models.DateTimeField(blank=True, null=True)),
                ('eta_date', models.DateField(blank=True, null=True)),
                ('received_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='boms.bom')),
                ('signoff_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signoff_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['bom', 'name'], name='boms_bomite_bom_id_b8e8d7_idx'), models.Index(fields=['signoff_assignee', 'signoff_status'], name='boms_bomite_signoff_e00991_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='bomtemplate',
            index=models.Index(fields=['owner', 'name'], name='boms_bomtem_owner_i_af7f89_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='procurementapproval',
            unique_together={('request', 'approver')},
        ),
    ]
