# Generated by Django 5.0.10 on 2026-01-03 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boms', '0002_bomitem_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BomCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_collaboration_invites', to=settings.AUTH_USER_MODEL)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborator_links', to='boms.bom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_collaborations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('bom', 'user')},
            },
        ),
        migrations.AddField(
            model_name='bom',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborating_boms', through='boms.BomCollaborator', to=settings.AUTH_USER_MODEL),
        ),
    ]
