# Generated by Django 5.0.10 on 2026-01-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
