# Generated by Django 5.0.10 on 2026-01-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notifications_email_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
