# Generated by Django 5.0.10 on 2026-01-02 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('BUG', 'Bug'), ('FEATURE', 'Feature'), ('UX', 'UX'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('message', models.TextField()),
                ('page_url', models.CharField(blank=True, max_length=500)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_REVIEW', 'In review'), ('RESOLVED', 'Resolved')], default='NEW', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='feedback_fe_status_91deca_idx'), models.Index(fields=['category', 'created_at'], name='feedback_fe_categor_5c7726_idx')],
            },
        ),
    ]
