# Generated by Django 5.0.10 on 2026-01-02 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('BOM', 'BOM'), ('CATALOG', 'Catalog'), ('PO', 'Purchase Order'), ('RFQ', 'RFQ'), ('QUOTE', 'Quote'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('query', models.CharField(blank=True, max_length=300)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='searches_se_user_id_fc8fb2_idx'), models.Index(fields=['entity_type', 'created_at'], name='searches_se_entity__94347b_idx')],
            },
        ),
    ]
