# Generated by Django 5.0.10 on 2026-01-02 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('vendor_url', models.URLField(blank=True)),
                ('currency', models.CharField(blank=True, max_length=20)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('tax_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'name'], name='catalog_cat_owner_i_dd025b_idx'), models.Index(fields=['vendor_name'], name='catalog_cat_vendor__757909_idx'), models.Index(fields=['category'], name='catalog_cat_categor_e0cfb9_idx')],
            },
        ),
    ]
