# Generated by Django 5.0.10 on 2026-01-02 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachments', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['owner', 'created_at'], name='attachments_owner_i_b8e723_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['bom'], name='attachments_bom_id_274508_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['purchase_order'], name='attachments_purchas_fd760d_idx'),
        ),
    ]
