# Generated by Django 5.0.10 on 2026-01-02 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0004_attachment_bill'),
    ]

    operations = []
