# Generated by Django 5.0.10 on 2026-01-02 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PARTIAL', 'Partial'), ('RECEIVED', 'Received'), ('CANCELED', 'Canceled')], default='DRAFT', max_length=20)),
                ('po_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('currency', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='boms.bom')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(blank=True, max_length=20)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('tax_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('link', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('ordered_at', models.DateTimeField(blank=True, null=True)),
                ('eta_date', models.DateField(blank=True, null=True)),
                ('received_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boms.bomitem')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase_orders.purchaseorder')),
            ],
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status', 'created_at'], name='purchase_or_status_646ec2_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['vendor_name'], name='purchase_or_vendor__bb85b8_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderitem',
            index=models.Index(fields=['purchase_order', 'name'], name='purchase_or_purchas_8cd46a_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderitem',
            index=models.Index(fields=['eta_date'], name='purchase_or_eta_dat_c3ebfa_idx'),
        ),
    ]
