# Generated by Django 5.0.10 on 2026-01-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='category',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
